### ISSUE TITLE
Allow entering "City, State" and pass "State" (if present) as "state code" to the API

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/weather-app#128]
The main input for the "one-call" API from OpenWeatherMap is lat/lon coordinates, so that's what we should consider the canonical location.

Storing the city/state is just for user-friendly display.

### Tasks

- [ ] Add `location.stateCode` to `store.ts`.
  - [ ] Update the `state` object to add `stateCode` to `location`.
  - [ ] Update `src/store/types.ts` as well.
  - [ ] Add a `SET_STATE_CODE` mutation to `store/mutations.ts` and a matching function in the `store.ts` `mutations: { }` section.
- [ ] In `LocationPicker.setCity`, if the new value contains a comma, call `city.split(',')` and store the first value as `location.city` (per current behavior) and the second as `location.stateCode` in the store (using the new `SET_STATE_CODE` mutation). Both values should be trimmed of surrounding whitespace (probably in the store mutation functions).
- [ ] Use the geolocation API to update the lat/lon coords in vuex whenever the city/state change.

**Comment by dave-burke** [comment]
The OpenWeather API has a location [query](https://openweathermap.org/api/geocoding-api) endpoint that takes comma delimited city, state, country, so there's no reason for us to do this kind of parsing.

This is being replaced by another story to implement more robust location picking like in the mock up.
