### ISSUE TITLE
Use browser Geolocation API to get the user's location automatically.

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/weather-app#129]
[Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) on MDN Web Docs.

### Tasks
- [x] Add a `BIconGeoAltFill` icon to the `LocationPicker` component (to the right of the City input).
- [x] Create a handler when the icon is clicked.
- [x] Create `src/services/GeolocationService.js` with a `getCurrentPosition` function.
- [x] Call `GeolocationService.getCurrentPosition` in the `BIconGeoAltFill` click handler and save result as `coords`.
- [x] Set `$store.location.lat` to `coords.latitude` and $store.location.lon` to coords.longitude`
- [x] Handle errors with a notice to the user. Consider a [Toast](https://bootstrap-vue.org/docs/components/toast).
- [x] Set `$store.location.city` based on the lat/lon. Not sure how to do this.

### Example code for getCurrentPosition service function

Based on the [MDN example](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#javascript).

```javascript
return new Promise((resolve, reject) => {
  if(!navigator.geolocation) {
    reject('Geolocation is not supported by your browser');
  }
  navigator.geolocation.getCurrentPosition(() => resolve(position.coords), () => reject('Unable to retrieve your location');
});
```

**Comment by mjp2233** [comment]
@dave-burke I just started on this task but am running into a couple of issues. First, I'm using a boostrap button was planning on calling the getCurrentPosition method in the Loctation Picker component but not sure if that's best practice. I have a feeling that isn't quite what "Create a handler" is refering to, did you have something in mind?

I'm also having issues getting the resolve(position.coords) to work in the GeoLocationService. I had something working for geolocation in the mitch/geo-location branch but it doesn't use promises so my approach of creating a 'resolve' constant is probably incorrect.

If you have time, I wouldn't mind if someone would take a look, set up a meeting, or talk at our next meeting?

I'll keep working on it this weekend, but thought I'd open it up to anyone to work on.
